export interface ResourceInfo {
	name: string;
	path: string;
	description: string;
	category: string;
	nonModel?: boolean;
}

export const resources: ResourceInfo[] = [
	{
		name: "AIAgentSessionAnchors",
		path: "aIAgentSessionAnchors",
		description: "Anchor points within AI agent sessions",
		category: "AI",
	},
	{
		name: "AIAgentSessionHistories",
		path: "aIAgentSessionHistories",
		description: "History records for AI agent sessions",
		category: "AI",
	},
	{
		name: "AIAgentSessions",
		path: "aIAgentSessions",
		description: "Active AI agent conversation sessions",
		category: "AI",
	},
	{
		name: "AIAgentSkills",
		path: "aIAgentSkills",
		description: "Skills assigned to AI agents",
		category: "AI",
	},
	{ name: "AIAgents", path: "aIAgents", description: "AI agent configurations", category: "AI" },
	{
		name: "AIProviders",
		path: "aIProviders",
		description: "AI service provider configurations (OpenAI, etc.)",
		category: "AI",
	},
	{
		name: "AISkillTools",
		path: "aISkillTools",
		description: "Tools available to AI skills",
		category: "AI",
	},
	{ name: "AISkills", path: "aISkills", description: "AI skill definitions", category: "AI" },
	{
		name: "AnalyticsDimCampuses",
		path: "analyticsDimCampuses",
		description: "Analytics dimension table for campuses",
		category: "Analytics",
	},
	{
		name: "AnalyticsDimFamilyCurrents",
		path: "analyticsDimFamilyCurrents",
		description: "Current family dimension records",
		category: "Analytics",
	},
	{
		name: "AnalyticsDimFamilyHeadOfHouseholds",
		path: "analyticsDimFamilyHeadOfHouseholds",
		description: "Head of household dimension records",
		category: "Analytics",
	},
	{
		name: "AnalyticsDimFamilyHistoricals",
		path: "analyticsDimFamilyHistoricals",
		description: "Historical family dimension records",
		category: "Analytics",
	},
	{
		name: "AnalyticsDimFinancialAccounts",
		path: "analyticsDimFinancialAccounts",
		description: "Financial account dimension records",
		category: "Analytics",
	},
	{
		name: "AnalyticsDimFinancialBatches",
		path: "analyticsDimFinancialBatches",
		description: "Financial batch dimension records",
		category: "Analytics",
	},
	{
		name: "AnalyticsDimPersonCurrents",
		path: "analyticsDimPersonCurrents",
		description: "Current person dimension records",
		category: "Analytics",
	},
	{
		name: "AnalyticsDimPersonHistoricals",
		path: "analyticsDimPersonHistoricals",
		description: "Historical person dimension records",
		category: "Analytics",
	},
	{
		name: "AnalyticsFactAttendances",
		path: "analyticsFactAttendances",
		description: "Attendance fact table for reporting",
		category: "Analytics",
	},
	{
		name: "AnalyticsFactFinancialTransactions",
		path: "analyticsFactFinancialTransactions",
		description: "Financial transaction fact table",
		category: "Analytics",
	},
	{
		name: "AnalyticsSourceAttendances",
		path: "analyticsSourceAttendances",
		description: "Source attendance data for analytics",
		category: "Analytics",
	},
	{
		name: "AnalyticsSourceCampuses",
		path: "analyticsSourceCampuses",
		description: "Source campus data for analytics",
		category: "Analytics",
	},
	{
		name: "AnalyticsSourceFamilyHistoricals",
		path: "analyticsSourceFamilyHistoricals",
		description: "Source family historical data",
		category: "Analytics",
	},
	{
		name: "AnalyticsSourceFinancialTransactions",
		path: "analyticsSourceFinancialTransactions",
		description: "Source financial transaction data",
		category: "Analytics",
	},
	{
		name: "AnalyticsSourceGivingUnits",
		path: "analyticsSourceGivingUnits",
		description: "Giving unit source data",
		category: "Analytics",
	},
	{
		name: "AnalyticsSourcePersonHistoricals",
		path: "analyticsSourcePersonHistoricals",
		description: "Source person historical data",
		category: "Analytics",
	},
	{
		name: "AttendanceCheckInSessions",
		path: "attendanceCheckInSessions",
		description: "Check-in session records",
		category: "Attendance & Check-in",
	},
	{
		name: "AttendanceCodes",
		path: "attendanceCodes",
		description: "Security codes for check-in labels",
		category: "Attendance & Check-in",
	},
	{
		name: "AttendanceOccurrences",
		path: "attendanceOccurrences",
		description: "Scheduled attendance occurrence instances",
		category: "Attendance & Check-in",
	},
	{
		name: "Attendances",
		path: "attendances",
		description: "Individual attendance records",
		category: "Attendance & Check-in",
	},
	{
		name: "CheckInLabels",
		path: "checkInLabels",
		description: "Label templates for check-in printing",
		category: "Attendance & Check-in",
	},
	{
		name: "BenevolenceRequestDocuments",
		path: "benevolenceRequestDocuments",
		description: "Documents attached to benevolence requests",
		category: "Benevolence",
	},
	{
		name: "BenevolenceRequests",
		path: "benevolenceRequests",
		description: "Benevolence assistance requests",
		category: "Benevolence",
	},
	{
		name: "BenevolenceResults",
		path: "benevolenceResults",
		description: "Results/outcomes of benevolence requests",
		category: "Benevolence",
	},
	{
		name: "BenevolenceTypes",
		path: "benevolenceTypes",
		description: "Types/categories of benevolence",
		category: "Benevolence",
	},
	{
		name: "BenevolenceWorkflows",
		path: "benevolenceWorkflows",
		description: "Workflows linked to benevolence requests",
		category: "Benevolence",
	},
	{ name: "Blocks", path: "blocks", description: "Page content blocks", category: "CMS & Pages" },
	{
		name: "BlockTypes",
		path: "blockTypes",
		description: "Block type definitions",
		category: "CMS & Pages",
	},
	{
		name: "HtmlContents",
		path: "htmlContents",
		description: "HTML content block data",
		category: "CMS & Pages",
	},
	{
		name: "Layouts",
		path: "layouts",
		description: "Page layout templates",
		category: "CMS & Pages",
	},
	{
		name: "LavaApplications",
		path: "lavaApplications",
		description: "Lava-powered web applications",
		category: "CMS & Pages",
	},
	{
		name: "LavaEndpoints",
		path: "lavaEndpoints",
		description: "Custom Lava API endpoints",
		category: "CMS & Pages",
	},
	{
		name: "LavaShortcodes",
		path: "lavaShortcodes",
		description: "Reusable Lava shortcode definitions",
		category: "CMS & Pages",
	},
	{
		name: "PageContexts",
		path: "pageContexts",
		description: "Page context configurations",
		category: "CMS & Pages",
	},
	{
		name: "PageRoutes",
		path: "pageRoutes",
		description: "URL route mappings for pages",
		category: "CMS & Pages",
	},
	{
		name: "PageShortLinks",
		path: "pageShortLinks",
		description: "Short URL links to pages",
		category: "CMS & Pages",
	},
	{ name: "Pages", path: "pages", description: "Rock CMS pages", category: "CMS & Pages" },
	{
		name: "SiteDomains",
		path: "siteDomains",
		description: "Domain names mapped to sites",
		category: "CMS & Pages",
	},
	{
		name: "Sites",
		path: "sites",
		description: "Rock CMS site configurations",
		category: "CMS & Pages",
	},
	{
		name: "Themes",
		path: "themes",
		description: "UI theme configurations",
		category: "CMS & Pages",
	},
	{
		name: "PersonalizationSegments",
		path: "personalizationSegments",
		description: "Audience segmentation for personalized content",
		category: "CMS & Pages",
	},
	{
		name: "CommunicationAttachments",
		path: "communicationAttachments",
		description: "File attachments on communications",
		category: "Communication",
	},
	{
		name: "CommunicationFlowCommunications",
		path: "communicationFlowCommunications",
		description: "Communications within a flow sequence",
		category: "Communication",
	},
	{
		name: "CommunicationFlowInstanceCommunicationConversions",
		path: "communicationFlowInstanceCommunicationConversions",
		description: "Conversion tracking for flow communications",
		category: "Communication",
	},
	{
		name: "CommunicationFlowInstanceCommunications",
		path: "communicationFlowInstanceCommunications",
		description: "Individual communications in a flow instance",
		category: "Communication",
	},
	{
		name: "CommunicationFlowInstanceRecipients",
		path: "communicationFlowInstanceRecipients",
		description: "Recipients in a communication flow instance",
		category: "Communication",
	},
	{
		name: "CommunicationFlowInstances",
		path: "communicationFlowInstances",
		description: "Running instances of communication flows",
		category: "Communication",
	},
	{
		name: "CommunicationFlows",
		path: "communicationFlows",
		description: "Automated multi-step communication sequences",
		category: "Communication",
	},
	{
		name: "CommunicationRecipients",
		path: "communicationRecipients",
		description: "Recipients of a communication",
		category: "Communication",
	},
	{
		name: "CommunicationResponseAttachments",
		path: "communicationResponseAttachments",
		description: "Attachments on communication responses",
		category: "Communication",
	},
	{
		name: "CommunicationResponses",
		path: "communicationResponses",
		description: "Responses/replies to communications",
		category: "Communication",
	},
	{
		name: "CommunicationTemplateAttachments",
		path: "communicationTemplateAttachments",
		description: "Attachments on communication templates",
		category: "Communication",
	},
	{
		name: "CommunicationTemplates",
		path: "communicationTemplates",
		description: "Reusable communication templates",
		category: "Communication",
	},
	{
		name: "Communications",
		path: "communications",
		description: "Email, SMS, and push communications",
		category: "Communication",
	},
	{
		name: "SmsActions",
		path: "smsActions",
		description: "SMS pipeline action configurations",
		category: "Communication",
	},
	{
		name: "SmsPipelines",
		path: "smsPipelines",
		description: "SMS message processing pipelines",
		category: "Communication",
	},
	{
		name: "SystemCommunications",
		path: "systemCommunications",
		description: "System-generated communication templates",
		category: "Communication",
	},
	{
		name: "SystemPhoneNumbers",
		path: "systemPhoneNumbers",
		description: "System phone numbers for SMS",
		category: "Communication",
	},
	{
		name: "AdaptiveMessageAdaptationSegments",
		path: "adaptiveMessageAdaptationSegments",
		description: "Audience segments for adaptive messages",
		category: "Communication",
	},
	{
		name: "AdaptiveMessageAdaptations",
		path: "adaptiveMessageAdaptations",
		description: "Content variations for adaptive messages",
		category: "Communication",
	},
	{
		name: "AdaptiveMessageCategories",
		path: "adaptiveMessageCategories",
		description: "Categories for adaptive messages",
		category: "Communication",
	},
	{
		name: "AdaptiveMessages",
		path: "adaptiveMessages",
		description: "Context-aware personalized messages",
		category: "Communication",
	},
	{
		name: "EmailSections",
		path: "emailSections",
		description: "Reusable email content sections",
		category: "Communication",
	},
	{
		name: "ConnectionActivityTypes",
		path: "connectionActivityTypes",
		description: "Types of connection activities",
		category: "Connections",
	},
	{
		name: "ConnectionOpportunities",
		path: "connectionOpportunities",
		description: "Connection opportunity definitions",
		category: "Connections",
	},
	{
		name: "ConnectionOpportunityCampuses",
		path: "connectionOpportunityCampuses",
		description: "Campus assignments for connection opportunities",
		category: "Connections",
	},
	{
		name: "ConnectionOpportunityConnectorGroups",
		path: "connectionOpportunityConnectorGroups",
		description: "Connector groups for opportunities",
		category: "Connections",
	},
	{
		name: "ConnectionOpportunityGroupConfigs",
		path: "connectionOpportunityGroupConfigs",
		description: "Group placement configs for opportunities",
		category: "Connections",
	},
	{
		name: "ConnectionOpportunityGroups",
		path: "connectionOpportunityGroups",
		description: "Groups linked to connection opportunities",
		category: "Connections",
	},
	{
		name: "ConnectionRequestActivities",
		path: "connectionRequestActivities",
		description: "Activity log for connection requests",
		category: "Connections",
	},
	{
		name: "ConnectionRequestWorkflows",
		path: "connectionRequestWorkflows",
		description: "Workflows triggered by connection requests",
		category: "Connections",
	},
	{
		name: "ConnectionRequests",
		path: "connectionRequests",
		description: "Individual connection requests",
		category: "Connections",
	},
	{
		name: "ConnectionStatusAutomations",
		path: "connectionStatusAutomations",
		description: "Automated status change rules",
		category: "Connections",
	},
	{
		name: "ConnectionStatuses",
		path: "connectionStatuses",
		description: "Status values for connection requests",
		category: "Connections",
	},
	{
		name: "ConnectionTypes",
		path: "connectionTypes",
		description: "Connection type configurations",
		category: "Connections",
	},
	{
		name: "ConnectionWorkflows",
		path: "connectionWorkflows",
		description: "Workflow triggers for connections",
		category: "Connections",
	},
	{
		name: "ContentChannelItemAssociations",
		path: "contentChannelItemAssociations",
		description: "Associations between content items",
		category: "Content & Media",
	},
	{
		name: "ContentChannelItemSlugs",
		path: "contentChannelItemSlugs",
		description: "URL slugs for content items",
		category: "Content & Media",
	},
	{
		name: "ContentChannelItems",
		path: "contentChannelItems",
		description: "Individual content channel entries",
		category: "Content & Media",
	},
	{
		name: "ContentChannelTypes",
		path: "contentChannelTypes",
		description: "Content channel type definitions",
		category: "Content & Media",
	},
	{
		name: "ContentChannels",
		path: "contentChannels",
		description: "Content channel configurations",
		category: "Content & Media",
	},
	{
		name: "ContentCollectionSources",
		path: "contentCollectionSources",
		description: "Sources for content collections",
		category: "Content & Media",
	},
	{
		name: "ContentCollections",
		path: "contentCollections",
		description: "Curated content collections",
		category: "Content & Media",
	},
	{
		name: "MediaAccounts",
		path: "mediaAccounts",
		description: "Media service provider accounts",
		category: "Content & Media",
	},
	{
		name: "MediaElements",
		path: "mediaElements",
		description: "Individual media items (videos, etc.)",
		category: "Content & Media",
	},
	{
		name: "MediaFolders",
		path: "mediaFolders",
		description: "Media organization folders",
		category: "Content & Media",
	},
	{
		name: "BinaryFiles",
		path: "binaryFiles",
		description: "Uploaded files and documents",
		category: "Content & Media",
	},
	{
		name: "BinaryFileTypes",
		path: "binaryFileTypes",
		description: "File type classifications",
		category: "Content & Media",
	},
	{
		name: "DataViewFilters",
		path: "dataViewFilters",
		description: "Filter definitions within data views",
		category: "Data & Reporting",
	},
	{
		name: "DataViews",
		path: "dataViews",
		description: "Saved data view queries",
		category: "Data & Reporting",
	},
	{
		name: "EntitySearches",
		path: "entitySearches",
		description: "Reusable entity search configurations",
		category: "Data & Reporting",
	},
	{
		name: "MergeTemplates",
		path: "mergeTemplates",
		description: "Document merge templates",
		category: "Data & Reporting",
	},
	{
		name: "PersistedDatasets",
		path: "persistedDatasets",
		description: "Cached/persisted dataset definitions",
		category: "Data & Reporting",
	},
	{
		name: "ReportFields",
		path: "reportFields",
		description: "Field definitions within reports",
		category: "Data & Reporting",
	},
	{
		name: "Reports",
		path: "reports",
		description: "Report configurations",
		category: "Data & Reporting",
	},
	{
		name: "EventCalendarContentChannels",
		path: "eventCalendarContentChannels",
		description: "Content channels linked to event calendars",
		category: "Events & Registration",
	},
	{
		name: "EventCalendarItems",
		path: "eventCalendarItems",
		description: "Events assigned to calendars",
		category: "Events & Registration",
	},
	{
		name: "EventCalendars",
		path: "eventCalendars",
		description: "Event calendar configurations",
		category: "Events & Registration",
	},
	{
		name: "EventItemAudiences",
		path: "eventItemAudiences",
		description: "Target audiences for events",
		category: "Events & Registration",
	},
	{
		name: "EventItemOccurrenceChannelItems",
		path: "eventItemOccurrenceChannelItems",
		description: "Content items for event occurrences",
		category: "Events & Registration",
	},
	{
		name: "EventItemOccurrenceGroupMaps",
		path: "eventItemOccurrenceGroupMaps",
		description: "Group mappings for event occurrences",
		category: "Events & Registration",
	},
	{
		name: "EventItemOccurrences",
		path: "eventItemOccurrences",
		description: "Specific event occurrence instances",
		category: "Events & Registration",
	},
	{
		name: "EventItems",
		path: "eventItems",
		description: "Event definitions",
		category: "Events & Registration",
	},
	{
		name: "RegistrationInstances",
		path: "registrationInstances",
		description: "Active registration instances",
		category: "Events & Registration",
	},
	{
		name: "RegistrationRegistrantFees",
		path: "registrationRegistrantFees",
		description: "Fee charges for registrants",
		category: "Events & Registration",
	},
	{
		name: "RegistrationRegistrants",
		path: "registrationRegistrants",
		description: "Individual registrants",
		category: "Events & Registration",
	},
	{
		name: "RegistrationSessions",
		path: "registrationSessions",
		description: "In-progress registration sessions",
		category: "Events & Registration",
	},
	{
		name: "RegistrationTemplateDiscounts",
		path: "registrationTemplateDiscounts",
		description: "Discount codes for registration",
		category: "Events & Registration",
	},
	{
		name: "RegistrationTemplateFeeItems",
		path: "registrationTemplateFeeItems",
		description: "Fee item options within templates",
		category: "Events & Registration",
	},
	{
		name: "RegistrationTemplateFees",
		path: "registrationTemplateFees",
		description: "Fee definitions in registration templates",
		category: "Events & Registration",
	},
	{
		name: "RegistrationTemplateFormFields",
		path: "registrationTemplateFormFields",
		description: "Form fields in registration templates",
		category: "Events & Registration",
	},
	{
		name: "RegistrationTemplateForms",
		path: "registrationTemplateForms",
		description: "Forms within registration templates",
		category: "Events & Registration",
	},
	{
		name: "RegistrationTemplatePlacements",
		path: "registrationTemplatePlacements",
		description: "Placement configurations for registrations",
		category: "Events & Registration",
	},
	{
		name: "RegistrationTemplates",
		path: "registrationTemplates",
		description: "Registration template definitions",
		category: "Events & Registration",
	},
	{
		name: "Registrations",
		path: "registrations",
		description: "Completed registration records",
		category: "Events & Registration",
	},
	{
		name: "FinancialAccounts",
		path: "financialAccounts",
		description: "Giving fund/account definitions",
		category: "Financial",
	},
	{
		name: "FinancialBatches",
		path: "financialBatches",
		description: "Transaction batch records",
		category: "Financial",
	},
	{
		name: "FinancialGateways",
		path: "financialGateways",
		description: "Payment gateway configurations",
		category: "Financial",
	},
	{
		name: "FinancialPaymentDetails",
		path: "financialPaymentDetails",
		description: "Payment method details for transactions",
		category: "Financial",
	},
	{
		name: "FinancialPersonBankAccounts",
		path: "financialPersonBankAccounts",
		description: "Person bank account records",
		category: "Financial",
	},
	{
		name: "FinancialPersonSavedAccounts",
		path: "financialPersonSavedAccounts",
		description: "Saved payment methods for people",
		category: "Financial",
	},
	{
		name: "FinancialPledges",
		path: "financialPledges",
		description: "Financial pledge commitments",
		category: "Financial",
	},
	{
		name: "FinancialScheduledTransactionDetails",
		path: "financialScheduledTransactionDetails",
		description: "Line items in scheduled transactions",
		category: "Financial",
	},
	{
		name: "FinancialScheduledTransactions",
		path: "financialScheduledTransactions",
		description: "Recurring transaction schedules",
		category: "Financial",
	},
	{
		name: "FinancialStatementTemplates",
		path: "financialStatementTemplates",
		description: "Giving statement templates",
		category: "Financial",
	},
	{
		name: "FinancialTransactionAlertTypes",
		path: "financialTransactionAlertTypes",
		description: "Alert type definitions for transactions",
		category: "Financial",
	},
	{
		name: "FinancialTransactionAlerts",
		path: "financialTransactionAlerts",
		description: "Transaction alert instances",
		category: "Financial",
	},
	{
		name: "FinancialTransactionDetails",
		path: "financialTransactionDetails",
		description: "Line item details within transactions",
		category: "Financial",
	},
	{
		name: "FinancialTransactionImages",
		path: "financialTransactionImages",
		description: "Check/receipt images for transactions",
		category: "Financial",
	},
	{
		name: "FinancialTransactionRefunds",
		path: "financialTransactionRefunds",
		description: "Refund records",
		category: "Financial",
	},
	{
		name: "FinancialTransactions",
		path: "financialTransactions",
		description: "Individual financial transactions",
		category: "Financial",
	},
	{
		name: "GroupHistoricals",
		path: "groupHistoricals",
		description: "Historical group records",
		category: "Groups & Membership",
	},
	{
		name: "GroupLocationHistoricals",
		path: "groupLocationHistoricals",
		description: "Historical group location records",
		category: "Groups & Membership",
	},
	{
		name: "GroupLocations",
		path: "groupLocations",
		description: "Physical locations assigned to groups",
		category: "Groups & Membership",
	},
	{
		name: "GroupMemberAssignments",
		path: "groupMemberAssignments",
		description: "Scheduling assignments for group members",
		category: "Groups & Membership",
	},
	{
		name: "GroupMemberHistoricals",
		path: "groupMemberHistoricals",
		description: "Historical group membership records",
		category: "Groups & Membership",
	},
	{
		name: "GroupMemberRequirements",
		path: "groupMemberRequirements",
		description: "Requirement completion for group members",
		category: "Groups & Membership",
	},
	{
		name: "GroupMemberScheduleTemplates",
		path: "groupMemberScheduleTemplates",
		description: "Schedule preferences for group members",
		category: "Groups & Membership",
	},
	{
		name: "GroupMemberWorkflowTriggers",
		path: "groupMemberWorkflowTriggers",
		description: "Workflow triggers on group member changes",
		category: "Groups & Membership",
	},
	{
		name: "GroupMembers",
		path: "groupMembers",
		description: "Group membership records",
		category: "Groups & Membership",
	},
	{
		name: "GroupRequirementTypes",
		path: "groupRequirementTypes",
		description: "Types of group membership requirements",
		category: "Groups & Membership",
	},
	{
		name: "GroupRequirements",
		path: "groupRequirements",
		description: "Requirements applied to groups",
		category: "Groups & Membership",
	},
	{
		name: "GroupScheduleExclusions",
		path: "groupScheduleExclusions",
		description: "Blackout dates for group scheduling",
		category: "Groups & Membership",
	},
	{
		name: "GroupSyncs",
		path: "groupSyncs",
		description: "Data sync configurations for groups",
		category: "Groups & Membership",
	},
	{
		name: "GroupTypeRoles",
		path: "groupTypeRoles",
		description: "Role definitions within group types",
		category: "Groups & Membership",
	},
	{
		name: "GroupTypes",
		path: "groupTypes",
		description: "Group type configurations",
		category: "Groups & Membership",
	},
	{
		name: "Groups",
		path: "groups",
		description: "Groups (small groups, teams, families, security roles)",
		category: "Groups & Membership",
	},
	{
		name: "Followings",
		path: "followings",
		description: "Entity following/subscription records",
		category: "Interactions & Engagement",
	},
	{
		name: "FollowingEventNotifications",
		path: "followingEventNotifications",
		description: "Notifications from following events",
		category: "Interactions & Engagement",
	},
	{
		name: "FollowingEventSubscriptions",
		path: "followingEventSubscriptions",
		description: "Subscriptions to following event types",
		category: "Interactions & Engagement",
	},
	{
		name: "FollowingEventTypes",
		path: "followingEventTypes",
		description: "Types of following events",
		category: "Interactions & Engagement",
	},
	{
		name: "FollowingSuggesteds",
		path: "followingSuggesteds",
		description: "Suggested entities to follow",
		category: "Interactions & Engagement",
	},
	{
		name: "FollowingSuggestionTypes",
		path: "followingSuggestionTypes",
		description: "Types of follow suggestions",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractionChannels",
		path: "interactionChannels",
		description: "Interaction tracking channels",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractionComponents",
		path: "interactionComponents",
		description: "Components within interaction channels",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractionDeviceTypes",
		path: "interactionDeviceTypes",
		description: "Device type classifications",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractionSessionLocations",
		path: "interactionSessionLocations",
		description: "Geographic locations for interaction sessions",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractionSessions",
		path: "interactionSessions",
		description: "User interaction sessions",
		category: "Interactions & Engagement",
	},
	{
		name: "Interactions",
		path: "interactions",
		description: "Individual interaction records",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractiveExperienceActions",
		path: "interactiveExperienceActions",
		description: "Actions in interactive experiences",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractiveExperienceAnswers",
		path: "interactiveExperienceAnswers",
		description: "Answers submitted in interactive experiences",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractiveExperienceOccurrences",
		path: "interactiveExperienceOccurrences",
		description: "Occurrences of interactive experiences",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractiveExperienceScheduleCampuses",
		path: "interactiveExperienceScheduleCampuses",
		description: "Campus schedules for interactive experiences",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractiveExperienceSchedules",
		path: "interactiveExperienceSchedules",
		description: "Schedules for interactive experiences",
		category: "Interactions & Engagement",
	},
	{
		name: "InteractiveExperiences",
		path: "interactiveExperiences",
		description: "Interactive experience configurations",
		category: "Interactions & Engagement",
	},
	{
		name: "PersonVieweds",
		path: "personVieweds",
		description: "Records of person profile views",
		category: "Interactions & Engagement",
	},
	{
		name: "LearningActivities",
		path: "learningActivities",
		description: "Learning activity definitions",
		category: "Learning",
	},
	{
		name: "LearningClassActivities",
		path: "learningClassActivities",
		description: "Activities assigned to classes",
		category: "Learning",
	},
	{
		name: "LearningClassActivityCompletions",
		path: "learningClassActivityCompletions",
		description: "Student activity completion records",
		category: "Learning",
	},
	{
		name: "LearningClassAnnouncements",
		path: "learningClassAnnouncements",
		description: "Class announcement posts",
		category: "Learning",
	},
	{
		name: "LearningClassContentPages",
		path: "learningClassContentPages",
		description: "Content pages within classes",
		category: "Learning",
	},
	{
		name: "LearningClasses",
		path: "learningClasses",
		description: "Learning class instances",
		category: "Learning",
	},
	{
		name: "LearningCourseRequirements",
		path: "learningCourseRequirements",
		description: "Prerequisites for courses",
		category: "Learning",
	},
	{
		name: "LearningCourses",
		path: "learningCourses",
		description: "Course definitions",
		category: "Learning",
	},
	{
		name: "LearningGradingSystemScales",
		path: "learningGradingSystemScales",
		description: "Grade scale definitions",
		category: "Learning",
	},
	{
		name: "LearningGradingSystems",
		path: "learningGradingSystems",
		description: "Grading system configurations",
		category: "Learning",
	},
	{
		name: "LearningParticipants",
		path: "learningParticipants",
		description: "Students enrolled in classes",
		category: "Learning",
	},
	{
		name: "LearningProgramCompletions",
		path: "learningProgramCompletions",
		description: "Program completion records",
		category: "Learning",
	},
	{
		name: "LearningPrograms",
		path: "learningPrograms",
		description: "Learning program configurations",
		category: "Learning",
	},
	{
		name: "LearningSemesters",
		path: "learningSemesters",
		description: "Semester/term definitions",
		category: "Learning",
	},
	{
		name: "Documents",
		path: "documents",
		description: "Documents attached to entities",
		category: "Notes & Documents",
	},
	{
		name: "DocumentTypes",
		path: "documentTypes",
		description: "Document type classifications",
		category: "Notes & Documents",
	},
	{
		name: "NoteAttachments",
		path: "noteAttachments",
		description: "File attachments on notes",
		category: "Notes & Documents",
	},
	{
		name: "NoteTypes",
		path: "noteTypes",
		description: "Note type definitions",
		category: "Notes & Documents",
	},
	{
		name: "NoteWatches",
		path: "noteWatches",
		description: "Watchers subscribed to note updates",
		category: "Notes & Documents",
	},
	{
		name: "Notes",
		path: "notes",
		description: "Notes attached to entities",
		category: "Notes & Documents",
	},
	{
		name: "SignatureDocumentTemplates",
		path: "signatureDocumentTemplates",
		description: "Electronic signature templates",
		category: "Notes & Documents",
	},
	{
		name: "SignatureDocuments",
		path: "signatureDocuments",
		description: "Signed document records",
		category: "Notes & Documents",
	},
	{
		name: "Snippets",
		path: "snippets",
		description: "Reusable text snippets",
		category: "Notes & Documents",
	},
	{
		name: "SnippetTypes",
		path: "snippetTypes",
		description: "Snippet type categories",
		category: "Notes & Documents",
	},
	{
		name: "NotificationMessageTypes",
		path: "notificationMessageTypes",
		description: "Notification message type definitions",
		category: "Notifications & Reminders",
	},
	{
		name: "NotificationMessages",
		path: "notificationMessages",
		description: "Individual notification messages",
		category: "Notifications & Reminders",
	},
	{
		name: "NotificationRecipients",
		path: "notificationRecipients",
		description: "Recipients of notifications",
		category: "Notifications & Reminders",
	},
	{
		name: "Notifications",
		path: "notifications",
		description: "Notification records",
		category: "Notifications & Reminders",
	},
	{
		name: "ReminderTypes",
		path: "reminderTypes",
		description: "Reminder type definitions",
		category: "Notifications & Reminders",
	},
	{
		name: "Reminders",
		path: "reminders",
		description: "Scheduled reminder records",
		category: "Notifications & Reminders",
	},
	{ name: "People", path: "people", description: "Person records", category: "People & Families" },
	{
		name: "PersonAliases",
		path: "personAliases",
		description: "Person alias/ID mappings",
		category: "People & Families",
	},
	{
		name: "PersonDuplicates",
		path: "personDuplicates",
		description: "Potential duplicate person records",
		category: "People & Families",
	},
	{
		name: "PersonPreferences",
		path: "personPreferences",
		description: "User preference settings",
		category: "People & Families",
	},
	{
		name: "PersonPreviousNames",
		path: "personPreviousNames",
		description: "Historical name records",
		category: "People & Families",
	},
	{
		name: "PersonScheduleExclusions",
		path: "personScheduleExclusions",
		description: "Personal scheduling blackout dates",
		category: "People & Families",
	},
	{
		name: "PersonSearchKeys",
		path: "personSearchKeys",
		description: "Alternate search keys for people",
		category: "People & Families",
	},
	{
		name: "PersonSignals",
		path: "personSignals",
		description: "Signal indicators on person records",
		category: "People & Families",
	},
	{
		name: "PersonalDevices",
		path: "personalDevices",
		description: "Mobile devices registered to people",
		category: "People & Families",
	},
	{
		name: "PersonalLinkSectionOrders",
		path: "personalLinkSectionOrders",
		description: "Ordering for personal link sections",
		category: "People & Families",
	},
	{
		name: "PersonalLinkSections",
		path: "personalLinkSections",
		description: "Sections grouping personal links",
		category: "People & Families",
	},
	{
		name: "PersonalLinks",
		path: "personalLinks",
		description: "Personal bookmark links",
		category: "People & Families",
	},
	{
		name: "PhoneNumbers",
		path: "phoneNumbers",
		description: "Phone number records",
		category: "People & Families",
	},
	{
		name: "BackgroundChecks",
		path: "backgroundChecks",
		description: "Background check records",
		category: "People & Families",
	},
	{
		name: "Assessments",
		path: "assessments",
		description: "Person assessment results",
		category: "People & Families",
	},
	{
		name: "AssessmentTypes",
		path: "assessmentTypes",
		description: "Assessment type definitions",
		category: "People & Families",
	},
	{
		name: "PrayerRequests",
		path: "prayerRequests",
		description: "Prayer request submissions",
		category: "Prayer",
	},
	{
		name: "CampusSchedules",
		path: "campusSchedules",
		description: "Schedules assigned to campuses",
		category: "Scheduling",
	},
	{
		name: "CampusTopics",
		path: "campusTopics",
		description: "Topic configurations for campuses",
		category: "Scheduling",
	},
	{
		name: "Campuses",
		path: "campuses",
		description: "Campus/location configurations",
		category: "Scheduling",
	},
	{
		name: "Locations",
		path: "locations",
		description: "Physical location records",
		category: "Scheduling",
	},
	{
		name: "Schedules",
		path: "schedules",
		description: "Schedule/recurring time definitions",
		category: "Scheduling",
	},
	{
		name: "ScheduleCategoryExclusions",
		path: "scheduleCategoryExclusions",
		description: "Category-level schedule blackouts",
		category: "Scheduling",
	},
	{
		name: "Devices",
		path: "devices",
		description: "Check-in kiosks and device configurations",
		category: "Scheduling",
	},
	{
		name: "AuthAuditLogs",
		path: "authAuditLogs",
		description: "Authentication audit trail",
		category: "Security & Auth",
	},
	{
		name: "AuthClaims",
		path: "authClaims",
		description: "OAuth/OIDC claim definitions",
		category: "Security & Auth",
	},
	{
		name: "AuthClients",
		path: "authClients",
		description: "OAuth client application registrations",
		category: "Security & Auth",
	},
	{
		name: "AuthScopes",
		path: "authScopes",
		description: "OAuth scope definitions",
		category: "Security & Auth",
	},
	{
		name: "Auths",
		path: "auths",
		description: "Entity security authorization records",
		category: "Security & Auth",
	},
	{
		name: "AuditDetails",
		path: "auditDetails",
		description: "Detailed audit change records",
		category: "Security & Auth",
	},
	{
		name: "Audits",
		path: "audits",
		description: "Entity audit records",
		category: "Security & Auth",
	},
	{
		name: "IdentityVerificationCodes",
		path: "identityVerificationCodes",
		description: "Verification code records",
		category: "Security & Auth",
	},
	{
		name: "IdentityVerifications",
		path: "identityVerifications",
		description: "Identity verification records",
		category: "Security & Auth",
	},
	{
		name: "RemoteAuthenticationSessions",
		path: "remoteAuthenticationSessions",
		description: "Remote auth session records",
		category: "Security & Auth",
	},
	{
		name: "UserLogins",
		path: "userLogins",
		description: "User login/credential records",
		category: "Security & Auth",
	},
	{
		name: "RequestFilters",
		path: "requestFilters",
		description: "Request filtering rules",
		category: "Security & Auth",
	},
	{
		name: "StepProgramCompletions",
		path: "stepProgramCompletions",
		description: "Program completion records",
		category: "Steps & Streaks",
	},
	{
		name: "StepPrograms",
		path: "stepPrograms",
		description: "Discipleship/growth program definitions",
		category: "Steps & Streaks",
	},
	{
		name: "StepStatuses",
		path: "stepStatuses",
		description: "Status values for steps",
		category: "Steps & Streaks",
	},
	{
		name: "StepTypePrerequisites",
		path: "stepTypePrerequisites",
		description: "Prerequisites between step types",
		category: "Steps & Streaks",
	},
	{
		name: "StepTypes",
		path: "stepTypes",
		description: "Step type definitions within programs",
		category: "Steps & Streaks",
	},
	{
		name: "StepWorkflowTriggers",
		path: "stepWorkflowTriggers",
		description: "Workflow triggers on step changes",
		category: "Steps & Streaks",
	},
	{
		name: "StepWorkflows",
		path: "stepWorkflows",
		description: "Workflows linked to steps",
		category: "Steps & Streaks",
	},
	{
		name: "Steps",
		path: "steps",
		description: "Individual step completion records",
		category: "Steps & Streaks",
	},
	{
		name: "StreakTypeExclusions",
		path: "streakTypeExclusions",
		description: "Exclusion dates for streak tracking",
		category: "Steps & Streaks",
	},
	{
		name: "StreakTypes",
		path: "streakTypes",
		description: "Streak type definitions",
		category: "Steps & Streaks",
	},
	{
		name: "Streaks",
		path: "streaks",
		description: "Individual engagement streak records",
		category: "Steps & Streaks",
	},
	{
		name: "AchievementAttempts",
		path: "achievementAttempts",
		description: "Achievement attempt records",
		category: "Steps & Streaks",
	},
	{
		name: "AchievementTypePrerequisites",
		path: "achievementTypePrerequisites",
		description: "Prerequisites for achievement types",
		category: "Steps & Streaks",
	},
	{
		name: "AchievementTypes",
		path: "achievementTypes",
		description: "Achievement type definitions",
		category: "Steps & Streaks",
	},
	{
		name: "Attributes",
		path: "attributes",
		description: "Entity attribute definitions",
		category: "System & Admin",
	},
	{
		name: "AttributeMatrices",
		path: "attributeMatrices",
		description: "Attribute matrix containers",
		category: "System & Admin",
	},
	{
		name: "AttributeMatricesItem",
		path: "attributeMatricesItem",
		description: "Items within attribute matrices",
		category: "System & Admin",
	},
	{
		name: "AttributeMatricesTemplate",
		path: "attributeMatricesTemplate",
		description: "Attribute matrix template definitions",
		category: "System & Admin",
	},
	{
		name: "AttributeQualifiers",
		path: "attributeQualifiers",
		description: "Attribute qualifier/config values",
		category: "System & Admin",
	},
	{
		name: "AutomationEvents",
		path: "automationEvents",
		description: "Automation event definitions",
		category: "System & Admin",
	},
	{
		name: "AutomationTriggers",
		path: "automationTriggers",
		description: "Automation trigger configurations",
		category: "System & Admin",
	},
	{
		name: "Badges",
		path: "badges",
		description: "Person badge configurations",
		category: "System & Admin",
	},
	{
		name: "Categories",
		path: "categories",
		description: "Category tree for organizing entities",
		category: "System & Admin",
	},
	{
		name: "DefinedTypes",
		path: "definedTypes",
		description: "Defined type dictionary definitions",
		category: "System & Admin",
	},
	{
		name: "DefinedValues",
		path: "definedValues",
		description: "Values within defined types",
		category: "System & Admin",
	},
	{
		name: "EntityIntents",
		path: "entityIntents",
		description: "Intent classifications for entities",
		category: "System & Admin",
	},
	{
		name: "EntitySetItems",
		path: "entitySetItems",
		description: "Items within entity sets",
		category: "System & Admin",
	},
	{
		name: "EntitySets",
		path: "entitySets",
		description: "Named sets of entity references",
		category: "System & Admin",
	},
	{
		name: "EntityTypes",
		path: "entityTypes",
		description: "Rock entity type registry",
		category: "System & Admin",
	},
	{
		name: "ExceptionLogs",
		path: "exceptionLogs",
		description: "Application error/exception logs",
		category: "System & Admin",
	},
	{
		name: "FieldTypes",
		path: "fieldTypes",
		description: "Field type definitions for attributes",
		category: "System & Admin",
	},
	{
		name: "Histories",
		path: "histories",
		description: "Entity change history records",
		category: "System & Admin",
	},
	{
		name: "HistoryLogins",
		path: "historyLogins",
		description: "Login history records",
		category: "System & Admin",
	},
	{
		name: "MetaFirstNameGenderLookups",
		path: "metaFirstNameGenderLookups",
		description: "First name to gender mapping data",
		category: "System & Admin",
	},
	{
		name: "MetaLastNameLookups",
		path: "metaLastNameLookups",
		description: "Last name metadata lookups",
		category: "System & Admin",
	},
	{
		name: "MetaNickNameLookups",
		path: "metaNickNameLookups",
		description: "Nickname mapping data",
		category: "System & Admin",
	},
	{
		name: "MetricCategories",
		path: "metricCategories",
		description: "Category assignments for metrics",
		category: "System & Admin",
	},
	{
		name: "MetricPartitions",
		path: "metricPartitions",
		description: "Metric partition definitions",
		category: "System & Admin",
	},
	{
		name: "MetricValuePartitions",
		path: "metricValuePartitions",
		description: "Partition values for metric entries",
		category: "System & Admin",
	},
	{
		name: "MetricValues",
		path: "metricValues",
		description: "Individual metric data points",
		category: "System & Admin",
	},
	{
		name: "Metrics",
		path: "metrics",
		description: "Metric/KPI definitions",
		category: "System & Admin",
	},
	{
		name: "NcoaHistories",
		path: "ncoaHistories",
		description: "National Change of Address history",
		category: "System & Admin",
	},
	{
		name: "PluginMigrations",
		path: "pluginMigrations",
		description: "Plugin database migration records",
		category: "System & Admin",
	},
	{
		name: "RelatedEntities",
		path: "relatedEntities",
		description: "Entity relationship mappings",
		category: "System & Admin",
	},
	{
		name: "RestActions",
		path: "restActions",
		description: "REST API action/endpoint definitions",
		category: "System & Admin",
	},
	{
		name: "RestControllers",
		path: "restControllers",
		description: "REST API controller definitions",
		category: "System & Admin",
	},
	{
		name: "ServiceJobHistories",
		path: "serviceJobHistories",
		description: "Background job execution history",
		category: "System & Admin",
	},
	{
		name: "ServiceJobs",
		path: "serviceJobs",
		description: "Scheduled background job definitions",
		category: "System & Admin",
	},
	{
		name: "ServiceLogs",
		path: "serviceLogs",
		description: "Service/integration log entries",
		category: "System & Admin",
	},
	{
		name: "AssetStorageProviders",
		path: "assetStorageProviders",
		description: "Cloud storage provider configurations",
		category: "System & Admin",
	},
	{
		name: "WebFarmNodeLogs",
		path: "webFarmNodeLogs",
		description: "Web farm node activity logs",
		category: "System & Admin",
	},
	{
		name: "WebFarmNodeMetrics",
		path: "webFarmNodeMetrics",
		description: "Web farm node performance metrics",
		category: "System & Admin",
	},
	{
		name: "WebFarmNodes",
		path: "webFarmNodes",
		description: "Web farm node registrations",
		category: "System & Admin",
	},
	{
		name: "TaggedItems",
		path: "taggedItems",
		description: "Items tagged with a specific tag",
		category: "Tags",
	},
	{
		name: "Tags",
		path: "tags",
		description: "Tag definitions for categorizing entities",
		category: "Tags",
	},
	{
		name: "SignalTypes",
		path: "signalTypes",
		description: "Signal type definitions for person indicators",
		category: "Tags",
	},
	{
		name: "WorkflowActionFormAttributes",
		path: "workflowActionFormAttributes",
		description: "Attributes on workflow action forms",
		category: "Workflows",
	},
	{
		name: "WorkflowActionFormSections",
		path: "workflowActionFormSections",
		description: "Sections within workflow action forms",
		category: "Workflows",
	},
	{
		name: "WorkflowActionForms",
		path: "workflowActionForms",
		description: "User entry forms for workflow actions",
		category: "Workflows",
	},
	{
		name: "WorkflowActionTypes",
		path: "workflowActionTypes",
		description: "Workflow action type definitions",
		category: "Workflows",
	},
	{
		name: "WorkflowActions",
		path: "workflowActions",
		description: "Individual workflow action instances",
		category: "Workflows",
	},
	{
		name: "WorkflowActivities",
		path: "workflowActivities",
		description: "Workflow activity instances",
		category: "Workflows",
	},
	{
		name: "WorkflowActivityTypes",
		path: "workflowActivityTypes",
		description: "Workflow activity type definitions",
		category: "Workflows",
	},
	{
		name: "WorkflowFormBuilderTemplates",
		path: "workflowFormBuilderTemplates",
		description: "Form builder template definitions",
		category: "Workflows",
	},
	{
		name: "WorkflowTriggers",
		path: "workflowTriggers",
		description: "Workflow trigger configurations",
		category: "Workflows",
	},
	{
		name: "WorkflowTypes",
		path: "workflowTypes",
		description: "Workflow type definitions",
		category: "Workflows",
	},
	{
		name: "Workflows",
		path: "workflows",
		description: "Workflow instances",
		category: "Workflows",
	},
	{
		name: "BlockActions",
		path: "blockActions",
		description: "Block action handler (non-model)",
		category: "CMS & Pages",
		nonModel: true,
	},
	{
		name: "Chat",
		path: "chat",
		description: "Real-time chat handler (non-model)",
		category: "Communication",
		nonModel: true,
	},
	{
		name: "CheckIn",
		path: "checkIn",
		description: "Check-in process handler (non-model)",
		category: "Attendance & Check-in",
		nonModel: true,
	},
	{
		name: "Controls",
		path: "controls",
		description: "UI control data provider (non-model)",
		category: "System & Admin",
		nonModel: true,
	},
	{
		name: "LavaApp",
		path: "lavaApp",
		description: "Lava application runner (non-model)",
		category: "CMS & Pages",
		nonModel: true,
	},
	{
		name: "Tv",
		path: "tv",
		description: "TV/Apple TV interface handler (non-model)",
		category: "CMS & Pages",
		nonModel: true,
	},
	{
		name: "Utilities",
		path: "utilities",
		description: "System utility functions (non-model)",
		category: "System & Admin",
		nonModel: true,
	},
	{
		name: "DataViewsActions",
		path: "dataViewsActions",
		description: "Custom actions for data views (non-model)",
		category: "Data & Reporting",
		nonModel: true,
	},
	{
		name: "FollowingsActions",
		path: "followingsActions",
		description: "Custom actions for followings (non-model)",
		category: "Interactions & Engagement",
		nonModel: true,
	},
	{
		name: "WorkflowsActions",
		path: "workflowsActions",
		description: "Custom actions for workflows (non-model)",
		category: "Workflows",
		nonModel: true,
	},
];

export function findResource(query: string): ResourceInfo | undefined {
	const lower = query.toLowerCase();
	return resources.find((r) => r.name.toLowerCase() === lower || r.path.toLowerCase() === lower);
}

export function listByCategory(): Record<string, ResourceInfo[]> {
	const grouped: Record<string, ResourceInfo[]> = {};
	for (const r of resources) {
		if (!grouped[r.category]) grouped[r.category] = [];
		grouped[r.category]?.push(r);
	}
	return grouped;
}
